logging:
    level:
        root: debug
        com.activiti6.www.workflow: info
server:
    port: 8081
    servlet:
        context-path: /
spring:
    application:
        name: workflow
    profiles:
        active: dev
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        content-type: text/html
        mode: LEGACYHTML5
        prefix: classpath:/static/
        suffix: .html
